.TH TABBED\-HJC 1 tabbed\-hjc\-VERSION
.SH NAME
tabbed\-hjc \- generic tabbed interface (Hui-Jun Chen (https://huijunchen9260.github.io/)'s build)
.SH SYNOPSIS
.B tabbed
.RB [ \-c ]
.RB [ \-d ]
.RB [ \-k ]
.RB [ \-s ]
.RB [ \-v ]
.RB [ \-g
.IR geometry ]
.RB [ \-n
.IR name ]
.RB [ \-p
.RB [ s {+/-} ] \fIpos\fR ]
.RB [ \-o
.IR normbgcol ]
.RB [ \-O
.IR normfgcol ]
.RB [ \-t
.IR selbgcol ]
.RB [ \-T
.IR selfgcol ]
.RB [ \-u
.IR urgbgcol ]
.RB [ \-U
.IR urgfgcol ]
.RB [ \-r
.IR narg ]
.RI [ "command ..." ]
.SH DESCRIPTION
.B tabbed
is a simple tabbed container for applications which support XEmbed. Tabbed
will then run the provided command with the xid of tabbed as appended
argument. (See EXAMPLES.) The automatic spawning of the command can be
disabled by providing the -s parameter. If no command is provided
tabbed will just print its xid and run no command.
.SH OPTIONS
.TP
.B \-c
close tabbed when the last tab is closed. Mutually exclusive with -f.
.TP
.B \-d
detaches tabbed from the terminal and prints its XID to stdout.
.TP
.B \-f
fill up tabbed again by spawning the provided command, when the last tab is
closed. Mutually exclusive with -c.
.TP
.BI \-g " geometry"
defines the X11 geometry string, which will fixate the height and width of
tabbed.
The syntax is
.RI [=][ width {xX} height ][{+-} xoffset {+-} yoffset ].
See
.BR XParseGeometry (3)
for further details.
.TP
.B \-k
close foreground tabbed client (instead of tabbed and all clients) when
WM_DELETE_WINDOW is sent.
.TP
.BI \-n " name"
will set the WM_CLASS attribute to
.I name.
.TP
.BR \-p " [" s {+-}] \fIpos\fR
will set the absolute or relative position of where to start a new tab. When
.I pos
is is given without 's' in front it is an absolute position. Then negative
numbers will be the position from the last tab, where -1 is the last tab.
If 's' is given, then
.I pos
is a relative position to the current selected tab. If this reaches the limits
of the tabs; those limits then apply.
.TP
.BI \-r " narg"
will replace the
.I narg
th argument in
.I command
with the window id, rather than appending it to the end.
.TP
.B \-s
will disable automatic spawning of the command.
.TP
.BI \-o " normbgcol"
defines the normal background color.
.RI # RGB ,
.RI # RRGGBB ,
and X color names are supported.
.TP
.BI \-O " normfgcol"
defines the normal foreground color.
.TP
.BI \-t " selbgcol"
defines the selected background color.
.TP
.BI \-T " selfgbcol"
defines the selected foreground color.
.TP
.BI \-u " urgbgcol"
defines the urgent background color.
.TP
.BI \-U " urgfgbcol"
defines the urgent foreground color.
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.TP
.B Super\-Shift
show tabs
.TP
.B Super\-Shift\-Return
open new tab
.TP
.B Super\-Shift\-a
attach window in current workspace. Require
.BR wmctrl
and windows manager / desktop environment supporting
.BR EWMH
to list windows in current workspace. Make sure you use
.B -c
argument for tabbed, i.e.,
.B tabbed -c software -embedarg
for every software.
.TP
.B Super\-Shift\-s
attach window by mouse selection.
.TP
.B Super\-Shift\-plus
attach all windows in current workspace. Require
.BR wmctrl
and windows manager / desktop environment supporting
.BR EWMH
to list windows in current workspace. Make sure you use
.B -c
argument for tabbed, i.e.,
.B tabbed -c software -embedarg
for every software.
.TP
.B Super\-Shift\-d
detach child window from current tabbed window. Make sure you use
.B -c
argument for tabbed, i.e.,
.B tabbed -c software -embedarg
for every software.
.TP
.B Super\-Shift\-minus
detach all child windows from current tabbed window. Make sure you use
.B -c
argument for tabbed, i.e.,
.B tabbed -c software -embedarg
for every software.
.TP
.B Super\-Shift\-[
hide current tab in current tabbed window.
.TP
.B Super\-Shift\-]
show hidden tab in current tabbed window by dmenu prompt.
.TP
.B Super\-Shift\-backslash
show all hidden tabs in current tabbed window.
.TP
.B Super\-Shift\-,
open dmenu to either create a new tab appending the entered string or select
an already existing tab.
.TP
.B Super\-Shift\-.
open dmenu to open terminal software. Modify function
.BR OPENTERMSOFT
in
.BR config.h
to fit your software and terminal
.TP
.B Super\-Shift\-slash
open new terminal with $PWD based on existing tabs. Modify function
.BR OPENTERM
in
.BR config.h
to fit your terminal
.TP
.B Super\-Shift\-j
previous tab
.TP
.B Super\-Shift\-k
next tab
.TP
.B Super\-Shift\-h
move selected tab one to the left
.TP
.B Super\-Shift\-l
move selected tab one to the right
.TP
.B Super\-Shift\-u
toggle autofocus of urgent tabs
.TP
.B Control\-Tab
toggle between the selected and last selected tab
.TP
.B Super\-Shift\-q
close tab
.TP
.B Ctrl\-u
focus next urgent tab
.TP
.B Super\-Shift\-[0..9]
jumps to nth tab
.TP
.B F11
Toggle fullscreen mode.
.SH EXAMPLES
$ tabbed surf -e
.TP
$ tabbed urxvt -embed
.TP
$ tabbed xterm -into
.TP
$ $(tabbed -d >/tmp/tabbed.xid); urxvt -embed $(</tmp/tabbed.xid);
.TP
$ tabbed -r 2 st -w '' -e tmux
.SH CUSTOMIZATION
.B tabbed
can be customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR st (1),
.BR xembed (1)
.SH BUGS
Please report them.
