#!/bin/sh

# Dependency: xprop, xdotool

xprop -id "$(xdotool getactivewindow)" | grep -v 'WM_CLASS(STRING) = "tabbed"' && tabbed -c -d | xargs -I {} xdotool windowreparent $(xdotool getactivewindow) "{}"
